# Generated by Django 5.0.3 on 2024-04-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TailorxApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
