# Generated by Django 5.0.3 on 2024-04-08 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorxApp', '0004_profile_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='tailor',
        ),
        migrations.AlterField(
            model_name='tailor',
            name='tailor_pictures',
            field=models.ManyToManyField(blank=True, related_name='tailors', to='TailorxApp.picture'),
        ),
        migrations.AddField(
            model_name='picture',
            name='tailor',
            field=models.ManyToManyField(related_name='pictures', to=settings.AUTH_USER_MODEL),
        ),
    ]
