# Generated by Django 5.0.3 on 2024-03-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorxApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='caption',
            field=models.CharField(default='No caption provided', max_length=200),
        ),
    ]
