# Generated by Django 5.0.3 on 2024-03-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorxApp', '0004_client_address_client_username_tailor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='business_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
