# Generated by Django 5.0.3 on 2024-03-27 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorxApp', '0005_tailor_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TailorxApp.state'),
        ),
    ]
