# Generated by Django 5.0.3 on 2024-04-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorxApp', '0006_alter_tailor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tailor',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tailor',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tailor',
            name='skills',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
