# Generated by Django 5.0.3 on 2024-04-08 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorxApp', '0005_remove_picture_tailor_alter_tailor_tailor_pictures_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='tailor',
        ),
        migrations.AddField(
            model_name='picture',
            name='tailor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to=settings.AUTH_USER_MODEL),
        ),
    ]
